#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Creates a list of top 25 graduate programs for political science
according to 
- US News ranking for 2005, 2010, 2015
- National Research Council's ranking for years 2005, 2010, 2015
"""
# https://www.nap.edu/catalog/12994/a-data-based-assessment-of-research-doctorate-programs-in-the-united-states-with-cd

NRC_2010 = [
"STANFORD UNIVERSITY",
"HARVARD UNIVERSITY",
"UNIVERSITY OF MICHIGAN-ANN ARBOR",
"COLUMBIA UNIVERSITY IN THE CITY OF NEW YORK",
"NEW YORK UNIVERSITY",
"MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
"PENN STATE UNIVERSITY",
"RICE UNIVERSITY",
"YALE UNIVERSITY",
"UNIVERSITY OF CALIFORNIA-SAN DIEGO",
"STATE UNIVERSITY OF NEW YORK AT BINGHAMTON",
"PRINCETON UNIVERSITY",
"UNIVERSITY OF CHICAGO",
"UNIVERSITY OF PITTSBURGH PITTSBURGH CAMPUS",
"UNIVERSITY OF CALIFORNIA-DAVIS",
"DUKE UNIVERSITY",
"WASHINGTON UNIVERSITY IN ST. LOUIS",
"FLORIDA STATE UNIVERSITY",
"UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL",
"UNIVERSITY OF WASHINGTON",
"GEORGE WASHINGTON UNIVERSITY",
"INDIANA UNIVERSITY AT BLOOMINGTON",
"UNIVERSITY OF ROCHESTER",
"UNIVERSITY OF CALIFORNIA-BERKELEY",
"UNIVERSITY OF ILLINOIS AT URBANA-CHAMPAIGN",
"STATE UNIVERSITY OF NEW YORK AT STONY BROOK",
"EMORY UNIVERSITY",
"MICHIGAN STATE UNIVERSITY",
"TEXAS A & M UNIVERSITY",
"UNIVERSITY OF ARIZONA",
"OHIO STATE UNIVERSITY MAIN CAMPUS",
"UNIVERSITY OF WISCONSIN-MADISON",
"VANDERBILT UNIVERSITY",
"UNIVERSITY OF CALIFORNIA-LOS ANGELES"
]

# https://www.usnews.com/best-graduate-schools/top-humanities-schools/political-science-rankings

USNEWS_2017 = [
"STANFORD UNIVERSITY",
"HARVARD UNIVERSITY",
"UNIVERSITY OF MICHIGAN-ANN ARBOR",
"COLUMBIA UNIVERSITY IN THE CITY OF NEW YORK",
"NEW YORK UNIVERSITY",
"MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
"PENN STATE UNIVERSITY",
"YALE UNIVERSITY",
"UNIVERSITY OF CALIFORNIA-SAN DIEGO",
"PRINCETON UNIVERSITY",
"UNIVERSITY OF CHICAGO",
"UNIVERSITY OF CALIFORNIA-DAVIS",
"DUKE UNIVERSITY",
"WASHINGTON UNIVERSITY IN ST. LOUIS",
"UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL",
"UNIVERSITY OF WASHINGTON",
"INDIANA UNIVERSITY AT BLOOMINGTON",
"UNIVERSITY OF ROCHESTER",
"UNIVERSITY OF CALIFORNIA-BERKELEY",
"UNIVERSITY OF ILLINOIS AT URBANA-CHAMPAIGN",
"EMORY UNIVERSITY",
"TEXAS A & M UNIVERSITY",
"OHIO STATE UNIVERSITY",
"UNIVERSITY OF WISCONSIN-MADISON",
"VANDERBILT UNIVERSITY",
"UNIVERSITY OF CALIFORNIA-LOS ANGELES",
"CORNELL UNIVERSITY",
"UNIVERSITY OF PENNSYLVANIA",
"NORTHWESTERN UNIVERSITY",
"UNIVERSITY OF TEXAS AUSTIN"
]


top25 = list(set(NRC_2010) & set(USNEWS_2017))
